#ifndef SEGGER_RTT_CONF_H
#define SEGGER_RTT_CONF_H

#define SEGGER_RTT_MAX_NUM_UP_BUFFERS     1
#define SEGGER_RTT_MAX_NUM_DOWN_BUFFERS  0

#define BUFFER_SIZE_UP                   64
#define SEGGER_RTT_PRINTF_BUFFER_SIZE     32

#define SEGGER_RTT_MODE_DEFAULT          SEGGER_RTT_MODE_NO_BLOCK_SKIP

#endif
